---
name: Test Coverage

on:
  workflow_call:

permissions:
      contents: read
      packages: write
      statuses: write


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python 3
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start Docker
        run: docker compose -f docker-compose.test.yml up -d

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install poetry
        run: pip install "poetry<2.0"

      - name: Generate req.txt file.
        run : poetry export -f requirements.txt --output requirements.txt --with dev

      - name: Install dependencies.
        run: pip install -r requirements.txt

      - name: Check lint
        run: make lint

      - run: mkdir coverage

      - name: Test
        run: bash scripts/test.sh
        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage
